{"subject": "[Bug 1117086] Automatic cleanup of old kernels not working", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 01 Dec 2018 00:47:41 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00000.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1117086", "http://bugzilla.opensuse.org/show_bug.cgi?id=1117086#c3"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1117086\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1117086#c3\n\nbob wheater <bwheater@xxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n                 CC|                            |bnc-team-screening@xxxxxxxx\n                   |                            |ovo.novell.com\n   Target Milestone|---                         |Leap 15.0\n              Flags|                            |needinfo?(bnc-team-screenin\n                   |                            |g@xxxxxxxxxxxxxxxxxxxxxx)\n\n--- Comment #3 from bob wheater <bwheater@xxxxxxx> ---\nWhat is the status of this bug report?\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 29 Dec 2018 14:15:41 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg02714.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522", "http://bugzilla.suse.com/show_bug.cgi?id=1102522#c12"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522#c12\n\n--- Comment #12 from Swamp Workflow Management <swamp@xxxxxxx> ---\nopenSUSE-SU-2018:4306-1: An update that solves four vulnerabilities and has 17\nfixes is now available.\n\nCategory: security (important)\nBug References:\n1047218,1074971,1080978,1081495,1084533,1086185,1094680,1095817,1098017,1102522,1104821,1105000,1108038,1113313,1113978,1114209,1118897,1118898,1118899,1119634,1119706\nCVE References: CVE-2018-16873,CVE-2018-16874,CVE-2018-16875,CVE-2018-7187\nSources used:\nopenSUSE Leap 15.0 (src):    containerd-1.1.2-lp150.4.3.1,\ncontainerd-kubic-1.1.2-lp150.4.3.1, docker-18.06.1_ce-lp150.5.6.1,\ndocker-kubic-18.06.1_ce-lp150.5.6.1,\ndocker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-lp150.5.3.1,\ndocker-runc-kubic-1.0.0rc5+gitr3562_69663f0bd4b6-lp150.5.3.1,\ngo-1.10.4-lp150.2.7.1, go1.10-1.10.7-lp150.2.1,\ngolang-github-docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1,\ngolang-github-docker-libnetwork-kubic-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1,\ngolang-packaging-15.0.11-lp150.2.3.1\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Fri, 28 Dec 2018 23:13:23 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg02704.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522", "http://bugzilla.suse.com/show_bug.cgi?id=1102522#c11"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522#c11\n\n--- Comment #11 from Swamp Workflow Management <swamp@xxxxxxx> ---\nSUSE-SU-2018:4297-1: An update that solves four vulnerabilities and has 17\nfixes is now available.\n\nCategory: security (important)\nBug References:\n1047218,1074971,1080978,1081495,1084533,1086185,1094680,1095817,1098017,1102522,1104821,1105000,1108038,1113313,1113978,1114209,1118897,1118898,1118899,1119634,1119706\nCVE References: CVE-2018-16873,CVE-2018-16874,CVE-2018-16875,CVE-2018-7187\nSources used:\nSUSE Linux Enterprise Module for Open Buildservice Development Tools 15 (src): \n  containerd-1.1.2-5.3.4, docker-18.06.1_ce-6.8.2,\ndocker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-6.3.4, go-1.10.4-3.6.2,\ngo1.10-1.10.7-1.5.3,\ngolang-github-docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-4.3.5,\ngolang-packaging-15.0.11-3.3.2\nSUSE Linux Enterprise Module for Containers 15 (src):   \ncontainerd-1.1.2-5.3.4, docker-18.06.1_ce-6.8.2,\ndocker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-6.3.4,\ngolang-github-docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-4.3.5\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Fri, 14 Dec 2018 15:41:19 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg01437.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\n\n\nSwamp Workflow Management <swamp@xxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n         Whiteboard|                            |ibs:running:9732:important\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1118032] Calibre wont open with erro 2 'it_wasnt_me.ttf' not found", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 01 Dec 2018 20:58:48 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00026.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1118032"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032\n\n\nPatrick Finie <maninredd@xxxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n           Found By|---                         |Community User\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1118032] Calibre wont open with erro 2 'it_wasnt_me.ttf' not found", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sun, 02 Dec 2018 23:09:53 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00066.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1118032", "http://bugzilla.opensuse.org/show_bug.cgi?id=1118032#c1", "https://download.opensuse.org/repositories/Documentation:/Tools/openSUSE_Leap_15.0/"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032#c1\n\n--- Comment #1 from Cor Blom <cornelis@xxxxxxxxx> ---\nI do not see this on my system. Calibre is starting fine on 15.0.\n\nI remember having seen this issue in the past, but I don't remember the\ndetails. I think it went away after a reinstall I did shortly after, which\nwould suggest it had something to do with the local system.\n\nCan you try calibre from Documentation:Tools? [1] Some time ago the ways fonts\nwere dealt with was changed in the package. It builds against a not updated\nversion of 15.0, but I think there are no relevant updates that should cause\ntrouble. If it does not start with a different error message, I'll provide a\nupdated build against update/Leap?15.0/\n\nBTW: The best way to update to suggested version is first uninstalling the old\none. Or ignoring the warning. It is a kind of change that rpm is not happy\nwith.\n\n[1]\nhttps://download.opensuse.org/repositories/Documentation:/Tools/openSUSE_Leap_15.0/\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1118032] Calibre wont open with erro 2 'it_wasnt_me.ttf' not found", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sun, 02 Dec 2018 18:32:54 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00060.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1118032"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032\n\n\nAndreas Stieger <astieger@xxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n                 CC|                            |cornelis@xxxxxxxxx,\n                   |                            |ecsos@xxxxxxxxxxx,\n                   |                            |jnweiger@xxxxxxxxx,\n                   |                            |Sascha.Manns@xxxxxxxxxx\n           Assignee|bnc-team-screening@xxxxxxxx |ecsos@xxxxxxxxxxx\n                   |ovo.novell.com              |\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1118032] Calibre wont open with erro 2 'it_wasnt_me.ttf' not found", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Mon, 10 Dec 2018 09:09:56 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00824.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1118032", "http://bugzilla.opensuse.org/show_bug.cgi?id=1118032#c3"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032#c3\n\nEric Schirra <ecsos@xxxxxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n             Status|NEW                         |RESOLVED\n         Resolution|---                         |WORKSFORME\n\n--- Comment #3 from Eric Schirra <ecsos@xxxxxxxxxxx> ---\n(In reply to Eric Schirra from comment #2)\nI use only Calibre from Documentation:Tools.\nAnd i have no error. calibre opens and run without error.\n\nBut i can dark remind that was trubble when something with fonts in package\nwas change.\n\nSo, please deinstall calibre and install it from Documentation:Tools.\n\nAnd Patrick, please report it if calibre from Documentation:Tools runs.\n\nNo reply, so i think it is no bug and i can close it.\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 08 Dec 2018 14:11:57 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00757.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522", "http://bugzilla.suse.com/show_bug.cgi?id=1102522#c7"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522#c7\n\n--- Comment #7 from Swamp Workflow Management <swamp@xxxxxxx> ---\nopenSUSE-RU-2018:4052-1: An update that has 6 recommended fixes can now be\ninstalled.\n\nCategory: recommended (moderate)\nBug References: 1047218,1086185,1094680,1095817,1102522,1108038\nCVE References: \nSources used:\nopenSUSE Leap 42.3 (src):    containerd-1.1.2-19.2, docker-18.06.1_ce-48.2,\ndocker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-5.2, go-1.10.4-40.1,\ngo1.10-1.10.4-2.2,\ngolang-github-docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-8.1,\ngolang-packaging-15.0.11-17.1\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1118032] New: Calibre wont open with erro 2 'it_wasnt_me.ttf' not found", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 01 Dec 2018 03:11:36 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00003.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1118032"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1118032\n\n\n            Bug ID: 1118032\n           Summary: Calibre wont open with erro 2 'it_wasnt_me.ttf' not\n                    found\n    Classification: openSUSE\n           Product: openSUSE Distribution\n           Version: Leap 15.0\n          Hardware: x86-64\n                OS: Other\n            Status: NEW\n          Severity: Normal\n          Priority: P5 - None\n         Component: Other\n          Assignee: bnc-team-screening@xxxxxxxxxxxxxxxxxxxxxx\n          Reporter: maninredd@xxxxxxxxx\n        QA Contact: qa-bugs@xxxxxxx\n          Found By: ---\n           Blocker: ---\n\nUser-Agent:       Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML,\nlike Gecko) Chrome/70.0.3538.102 Safari/537.36\nBuild Identifier: \n\n~> calibre\nqt5ct: using qt5ct plugin\nTraceback (most recent call last):\n  File \"/usr/bin/calibre\", line 20, in <module>\n    sys.exit(calibre())\n  File \"/usr/lib64/calibre/calibre/gui_launch.py\", line 73, in calibre\n    main(args)\n  File \"/usr/lib64/calibre/calibre/gui2/main.py\", line 567, in main\n    gui_debug=gui_debug)\n  File \"/usr/lib64/calibre/calibre/gui2/main.py\", line 391, in run_gui\n    app.load_builtin_fonts(scan_for_fonts=True)\n  File \"/usr/lib64/calibre/calibre/gui2/__init__.py\", line 927, in\nload_builtin_fonts\n    load_builtin_fonts()\n  File \"/usr/lib64/calibre/calibre/gui2/__init__.py\", line 745, in\nload_builtin_fonts\n    with open(ff, 'rb') as s:\nIOError: [Errno 2] No such file or directory:\n\"/usr/share/calibre/fonts/liberation/It_wasn't_me.ttf\"\n\n\nUnsure what the issue is.  tried forcing a reinstall and switching versions. \nThis did not help.  I did not test any version older than one update back, so i\nam unsure if there is a regression that appeared since i last had calibre\nworking.\n\n\nReproducible: Always\n\nSteps to Reproduce:\n1.open calibre\n2.nothing happens\n3.open calibre in a terminal\n4. Traceback (most recent call last):\n  File \"/usr/bin/calibre\", line 20, in <module>\n    sys.exit(calibre())\n  File \"/usr/lib64/calibre/calibre/gui_launch.py\", line 73, in calibre\n    main(args)\n  File \"/usr/lib64/calibre/calibre/gui2/main.py\", line 567, in main\n    gui_debug=gui_debug)\n  File \"/usr/lib64/calibre/calibre/gui2/main.py\", line 391, in run_gui\n    app.load_builtin_fonts(scan_for_fonts=True)\n  File \"/usr/lib64/calibre/calibre/gui2/__init__.py\", line 927, in\nload_builtin_fonts\n    load_builtin_fonts()\n  File \"/usr/lib64/calibre/calibre/gui2/__init__.py\", line 745, in\nload_builtin_fonts\n    with open(ff, 'rb') as s:\nIOError: [Errno 2] No such file or directory:\n\"/usr/share/calibre/fonts/liberation/It_wasn't_me.ttf\"\n\nActual Results:  \nCalibre didnt open\n\nExpected Results:  \nCalibre opening\n\nSystem Information:\nSystem:    Host: [redacted] Kernel: 4.19.2-1.g8adee6e-default x86_64 bits: 64\nDesktop: Xfce 4.12.4\n           Distro: openSUSE Leap 15.0\nMachine:   Device: server System: Dell product: PowerEdge T410 serial: N/A\n           Mobo: Dell model: 0H19HD v: A03 serial: N/A BIOS: Dell v: 1.14.0\ndate: 05/30/2018\nCPU(s):    2 Hexa core Intel Xeon X5660s (-HT-MCP-SMP-) cache: 24576 KB\n           clock speeds: max: 1596 MHz 1: 1596 MHz 2: 1596 MHz 3: 1595 MHz 4:\n1596 MHz 5: 1596 MHz 6: 1596 MHz\n           7: 1596 MHz 8: 1596 MHz 9: 1596 MHz 10: 1596 MHz 11: 1596 MHz 12:\n1596 MHz 13: 1596 MHz 14: 1596 MHz\n           15: 1596 MHz 16: 1595 MHz 17: 1596 MHz 18: 1595 MHz 19: 1596 MHz 20:\n1596 MHz 21: 1596 MHz\n           22: 1596 MHz 23: 1596 MHz 24: 1596 MHz\nGraphics:  Card: NVIDIA GP108 [GeForce GT 1030]\n           Display Server: x11 (X.Org 1.20.3 ) drivers: nvidia (unloaded:\nmodesetting,fbdev,nv,vesa,nouveau)\n           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz\n           OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 version: 4.6.0 NVIDIA\n415.13\nAudio:     Card-1 NVIDIA GP108 High Definition Audio Controller driver:\nsnd_hda_intel\n           Card-2 Logitech HD Pro Webcam C920 driver: USB Audio\n           Card-3 Logitech Clear Chat Comfort USB Headset driver: USB Audio\n           Card-4 Logitech V20 portable speakers (USB powered) driver: USB\nAudio\n           Sound: Advanced Linux Sound Architecture v:\nk4.19.2-1.g8adee6e-default\nNetwork:   Card-1: Broadcom NetXtreme II BCM5716 Gigabit Ethernet driver: bnx2\n           IF: em1 state: up speed: 1000 Mbps duplex: full mac:\n78:2b:cb:34:0f:df\n           Card-2: Broadcom NetXtreme II BCM5716 Gigabit Ethernet driver: bnx2\n           IF: em2 state: down mac: 78:2b:cb:34:0f:e0\nDrives:    HDD Total Size: 5966.2GB (14.2% used)\n           ID-1: /dev/sda model: PERC_6/i_Adapter size: 159.5GB\n           ID-2: /dev/sdb model: PERC_6/i_Adapter size: 159.5GB\n           ID-3: /dev/sdc model: PERC_6/i_Adapter size: 999.7GB\n           ID-4: /dev/sdd model: PERC_6/i_Adapter size: 639.5GB\n           ID-5: /dev/sde model: ST4000DM000 size: 4000.8GB\n           ID-6: USB /dev/sdf model: DataTraveler_2.0 size: 4.0GB\n           ID-7: USB /dev/sdg model: Internal_Storage size: 3.3GB\nPartition: ID-1: / size: 143G used: 37G (26%) fs: ext4 dev: /dev/sda2\n           ID-2: /home size: 147G used: 139G (96%) fs: ext4 dev: /dev/sdb1\n           ID-3: swap-1 size: 4.09GB used: 0.00GB (0%) fs: swap dev: /dev/sda1\nSensors:   System Temperatures: cpu: 27.0C mobo: N/A gpu: 35C\n           Fan Speeds (in rpm): cpu: N/A\nInfo:      Processes: 532 Uptime: 12 days 19:13 Memory: 11339.0/64405.1MB\nClient: Shell (bash) inxi: 2.3.40 \n\nInstalled packages\n\ncalibre-3.27.1-lp150.3.15.1.x86_64\n\npython-2.7.14-lp150.6.3.2.x86_64\n\npython3-3.6.5-lp150.2.3.1.x86_64\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1020429] VUL-0: kernel-source: crash by spawning mcrypt(alg) with incompatible algorithm", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 01 Dec 2018 03:02:30 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00002.html", "reference_link": ["http://bugzilla.novell.com/show_bug.cgi?id=1020429"], "msg_body": "\n\n\nhttp://bugzilla.novell.com/show_bug.cgi?id=1020429\n\n\nSMASH SMASH <smash_bz@xxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n         Whiteboard|                            |\n                   |CVSSv2:RedHat:CVE-2016-1014 |CVSSv2:RedHat:CVE-2016-1014\n                   |7:4.9:(AV:L/AC:L/Au:N/C:N/I |7:4.9:(AV:L/AC:L/Au:N/C:N/I\n                   |:N/A:C)                     |:N/A:C)\n                   |CVSSv2:SUSE:CVE-2016-10147: |CVSSv2:SUSE:CVE-2016-10147:\n                   |4.9:(AV:L/AC:L/Au:N/C:N/I:N |4.9:(AV:L/AC:L/Au:N/C:N/I:N\n                   |/A:C)                       |/A:C)\n                   |CVSSv2:NVD:CVE-2016-10147:4 |CVSSv2:NVD:CVE-2016-10147:4\n                   |.9:(AV:L/AC:L/Au:N/C:N/I:N/ |.9:(AV:L/AC:L/Au:N/C:N/I:N/\n                   |A:C)                        |A:C)\n                   |CVSSv3:RedHat:CVE-2016-1014 |CVSSv3:RedHat:CVE-2016-1014\n                   |7:5.5:(AV:L/AC:L/PR:L/UI:N/ |7:5.5:(AV:L/AC:L/PR:L/UI:N/\n                   |S:U/C:N/I:N/A:H)            |S:U/C:N/I:N/A:H)\n                   |                            |CVSSv3:NVD:CVE-2016-10147:5\n                   |                            |.5:(AV:L/AC:L/PR:L/UI:N/S:U\n                   |                            |/C:N/I:N/A:H)\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sun, 30 Dec 2018 23:39:46 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg02754.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\n\n\nSwamp Workflow Management <swamp@xxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n         Whiteboard|ibs:running:9732:important  |\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sun, 02 Dec 2018 07:42:48 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00037.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\n\n\nSwamp Workflow Management <swamp@xxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n         Whiteboard|ibs:running:9328:moderate   |\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1102522] Docker v18.06-ce upgrade.", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 01 Dec 2018 01:47:55 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00001.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1102522", "http://bugzilla.suse.com/show_bug.cgi?id=1102522#c6"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522\nhttp://bugzilla.suse.com/show_bug.cgi?id=1102522#c6\n\nAleksa Sarai <asarai@xxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n             Status|NEW                         |RESOLVED\n         Resolution|---                         |FIXED\n\n--- Comment #6 from Aleksa Sarai <asarai@xxxxxxxx> ---\nReleased.\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1117086] Automatic cleanup of old kernels not working", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Sat, 08 Dec 2018 10:38:00 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00746.html", "reference_link": ["http://bugzilla.opensuse.org/show_bug.cgi?id=1117086", "http://bugzilla.opensuse.org/show_bug.cgi?id=1117086#c6"], "msg_body": "\n\n\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1117086\nhttp://bugzilla.opensuse.org/show_bug.cgi?id=1117086#c6\n\nPhilippe Cond\u00e9 <conde.philippe@xxxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n                 CC|                            |conde.philippe@xxxxxxxxx\n\n--- Comment #6 from Philippe Cond\u00e9 <conde.philippe@xxxxxxxxx> ---\nHello,\n\nI see the same problem in Tumbleweed but this seems related to the kernel-xen\nrequirement. I use the Xen Hypervisor but this problem in on the dom0 server\nnot a VM\n\nif I start purge-kernels i receive the next error\n# purge-kernels\nerror: Failed dependencies:\n        kernel-xen is needed by (installed)\npatterns-server-xen_server-20180718-1.1.x86_64\n        kernel-xen is needed by (installed)\npatterns-server-xen_server-20180718-1.1.x86_64\n        kernel-xen is needed by (installed)\npatterns-server-xen_server-20180718-1.1.x86_64\n        kernel-xen is needed by (installed)\npatterns-server-xen_server-20180718-1.1.x86_64\n/sbin/purge-kernels: giving up.\n\nif I search the requirements\n# rpm -q --requires patterns-server-xen_server\nkernel-xen\npattern() = basesystem\nrpmlib(CompressedFileNames) <= 3.0.4-1\nrpmlib(FileDigests) <= 4.6.0-1\nrpmlib(PayloadFilesHavePrefix) <= 4.0-1\nrpmlib(PayloadIsXz) <= 5.2-1\ntftp\nxen\nxen-libs\nxen-tools\n\n\nAs the kernel-xen has been removed/changed in 2016 maybe these requirements are\nnot more needed?\n\nRegards\nPhilippe\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
{"subject": "[Bug 1117086] Automatic cleanup of old kernels not working", "origin": "bugzilla_noreply@xxxxxxxxxx", "date": "Mon, 03 Dec 2018 12:29:46 +0000", "src_link": "https://lists.opensuse.org/opensuse-bugs/2018-12/msg00142.html", "reference_link": ["http://bugzilla.suse.com/show_bug.cgi?id=1117086", "http://bugzilla.suse.com/show_bug.cgi?id=1117086#c5"], "msg_body": "\n\n\nhttp://bugzilla.suse.com/show_bug.cgi?id=1117086\nhttp://bugzilla.suse.com/show_bug.cgi?id=1117086#c5\n\nMichael Schr\u00f6der <mls@xxxxxxxx> changed:\n\n           What    |Removed                     |Added\n----------------------------------------------------------------------------\n                 CC|                            |mls@xxxxxxxx\n           Assignee|bnc-team-screening@xxxxxxxx |daniel.molkentin@xxxxxxxx\n                   |ovo.novell.com              |\n              Flags|needinfo?(bnc-team-screenin |\n                   |g@xxxxxxxxxxxxxxxxxxxxxx)   |\n\n--- Comment #5 from Michael Schr\u00f6der <mls@xxxxxxxx> ---\n$ osc meta user dmolkentin\n<person>\n  <login>dmolkentin</login>\n  <email>daniel.molkentin@xxxxxxxx</email>\n  <realname>Daniel Molkentin</realname>\n  <state>confirmed</state>\n  <watchlist/>\n</person>\n\nReassigned to Daniel.\n\n-- \nYou are receiving this mail because:\nYou are on the CC list for the bug.\n\n\n\n\n"}
